name: Cam's travel blog
description: 
meta_description: "cameron smith's travel blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl:
domain_name: "camoverride.com"
google_analytics:
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Cameron Smith"

# Disqus config
disqus-shortname: ""
